
name: news_flutter
description: A new Flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  nb_utils: 3.1.4
  dots_indicator: ^0.0.4
  google_fonts: 1.1.0
  flutter_custom_clippers: 1.1.1
  share: 0.6.4+3
  flutter_svg: 0.17.4
  http: 0.12.0+4
  intl: 0.16.1
  html: 0.14.0+3
  image_picker:
  flutter_staggered_grid_view: 0.3.0
  url_launcher: 5.5.0
  open_appstore: 1.0.2
  flutter_widget_from_html: 0.4.2
  html_unescape: ^1.0.1+3
  cached_network_image: ^2.0.0-rc
  flutter_linkify: 3.1.3
  linkable: 1.0.5
  #flutter_wordpress_content: 1.0.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - Images/News/
     - Images/News/flags/

  fonts:
    - family: Jost
      fonts:
        - asset: fonts/SFUIText-Regular.ttf
        - asset: fonts/SFUIText-Medium.ttf
        - asset: fonts/SFUIText-Bold.ttf
        - asset: fonts/SFUIText-Semibold.ttf

